pipeline {
    agent any
    tools {
        maven 'Maven' //引号里的Maven不要改
    }
    stages {
        stage('Test') {
            steps {
                withSonarQubeEnv('SonarQube') { //引号里的SonarQube不要改
                    sh 'mvn -f CDAR/pom.xml clean sonar:sonar'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -f CDAR/pom.xml package'
                archive 'CDAR/target/CDAR.war' //制品路径需要修改
            }
        }
        stage('Deploy') {
            steps { //所有的group1_demo需要修改
                sh 'docker stop WineTasters_CDAR || true'
                sh 'docker rm WineTasters_CDAR || true'
                sh 'docker run --name WineTasters_CDAR -p 19996:8080 -d dordoka/tomcat' //端口11111需要修改
                sh 'docker cp CDAR/target/CDAR.war WineTasters_CDAR:/opt/tomcat/webapps/' //制品路径需要修改
            }
        }
    }
}
